apiVersion: v1
kind: Service
metadata:
    name: "k8sprod-689a"
    labels:
        app: "k8sprod-689a"
spec:
    type: LoadBalancer
    ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "k8sprod-689a"